### ISSUE TITLE
GWAS with genotype x phenotype interaction

### ISSUE THREAD

**Issue by MrLocuace** [Atkinson-Lab/Tractor#12]
Hello:
I was wondering whether or not it is possible to run a GWAS with genotype x phenotype interaction using TRACTOR and how would this be done.
Thank you for your help

**Comment by JasonTan-code** [comment]
Hi, 

Thanks for your interest in Tractor. We currently haven’t built genotype X phenotype interaction yet, since the implementation is not very trivial. Take African American as an example, we may study the interaction of AFR * ENV, or EUR * ENV, or even AFR * EUR * ENV. Things can be a bit complicated with interaction terms included. You may need to manually modify the RunTractor.py if you hope to add interaction terms. 

Feel free to contact us if you encountered some implementation issues.
Taotao
